DOC Update README.md for CMS 5
silverstripe/silverstripe-securityreport pull request #65
Opened 2023-04-19 04:25 UTC by GuySartorelli

## Issue

- https://github.com/silverstripe/.github/issues/20

2023-04-24 01:45 UTC, sabina-talipova requested changes

2023-04-24 01:45 UTC, sabina-talipova commented on README.md
Could you, please, remove this section.
https://github.com/silverstripe/silverstripe-securityreport/blob/f85ac0e72d3cf6d9a3239bb39d1aa6f2e41290af/README.md?plain=1#L14-L18

2023-04-24 04:38 UTC, GuySartorelli commented on README.md
Done

2023-04-25 20:26 UTC, sabina-talipova approved these changes
LGTM

2023-04-25 20:27 UTC, merged